### ISSUE TITLE
recursion not supported in modules

### ISSUE THREAD

**Issue by KitWallace** [EinsteinsWorkshop/BlocksCAD#22]
recursive call in a module generates a syntax error even though the resultant OpenSCAD code executes correctly.

**Comment by mattminuti** [comment]
Would you mind providing an example so we can track this down?

**Comment by yoderjen** [comment]
Recursion sometimes works, and sometimes doesn't.  The problem is buried somewhere in our parser.

This recursive menger sponge works, with the loops directly inside the module def.:
![working_recursive_sponge](https://cloud.githubusercontent.com/assets/10271662/11277427/88940c5c-8eb4-11e5-92e2-c5dead5e48e1.png)

while this rearrangement of the same code fails with a parsing error:

![failing_recursive_sponge](https://cloud.githubusercontent.com/assets/10271662/11277480/bae4b2ba-8eb4-11e5-93be-cdafcbea0ddd.png)

**Comment by yoderjen** [comment]
So sometimes you can rearrange the code in a way to make recursion work.  I don't know exactly where in the parser the problem is at this time.  It is going on our long list of things to fix in the parser, thanks.

**Comment by KitWallace** [comment]
This was my simple example:

![image](https://cloud.githubusercontent.com/assets/191645/11279374/1e35dbd6-8ee8-11e5-916e-82e6f363db36.png)

**Comment by mattminuti** [comment]
Adding an else condition with anything in it makes it work, so maybe the parser doesn't know how to handle the exit case...? Thanks for the example, it'll help!

**Comment by yoderjen** [comment]
As of version 1.7.0, our parser is much more flexible in how you can code recursive modules.  If you have any examples that still don't work in 1.7.0, please let me know.
