### ISSUE TITLE
Non-manifold issues with simple geometry

### ISSUE THREAD

**Issue by mattminuti** [EinsteinsWorkshop/BlocksCAD#25]
![screenshot](https://cloud.githubusercontent.com/assets/450935/12877273/b5a68918-cdde-11e5-8841-a01ca1ca6688.png)

Some simple geometry results in non-manifold STLs - example attached. Looks like some bad triangulation. All earlier versions of BlocksCAD show this issue, as does the current version of OpenJSCAD. OpenSCAD 2014.01 produces perfectly fine STLs.

**Comment by yoderjen** [comment]
The csg.js geometry engine produces meshes with T-junctions.  Due to rounding, these stl's are technically non-manifold.  In practice, they are fine for printing, and work fine with many slicers including Cura, Simplify3D, MakerBot Slicer, and MatterControl.  The stls can also be cleaned in an app like netfabb.

This is on our known bug list, but is not at the top of the priority queue.  The OpenJScad community occasionally updates csg.js, and I know they are aware of this issue as well.
